import type { Metadata } from "next";
import localFont from "next/font/local";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import CartContext from "@/context/CartContext";

const urbanist = Urbanist({
   subsets: ["latin"],
});
const geistSans = localFont({
   src: "./fonts/GeistVF.woff",
   variable: "--font-geist-sans",
   weight: "100 900",
});
const geistMono = localFont({
   src: "./fonts/GeistMonoVF.woff",
   variable: "--font-geist-mono",
   weight: "100 900",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${urbanist.className}  antialiased`}>
            <AntdRegistry>
               <CartContext>{children}</CartContext>
            </AntdRegistry>
         </body>
      </html>
   );
}
